
 const translations = {
  th: {
    product_title: "สินค้าและบริการ",
    product_mainpage: "สินค้า",
    product_keyword: "รหัสสินค้า/ชื่อสินค้า",
    product_button_create: "เพิ่มสินค้าใหม่",
    product_table_code: "รหัสสินค้า",
    product_table_name1: "ชื่อสินค้าไทย",
    product_table_name2: "ชื่อสินค้าอังกฤษ",
    product_table_price: "ราคา/หน่วย",
    price: "ราคา",
    status: "สถานะ",
    createdate: "วันที่สร้าง",
    createby: "สร้างโดย",
    updatedate: "วันที่แก้ไข",
    updateby: "แก้ไขโดย",
    delete: "ลบ",
    update: "แก้ไข",
    firstpage: "หน้าแรก",
    prevpage: "ก่อนหน้า",
    lastpage: "หน้าสุดท้าย",
    number: "จำนวน",
    page: "หน้า",
    of: "จาก",
    nextpage: "ถัดไป",
    record: "รายการ",
    reset: "รีเซ็ต",
    back: "หน้าหลัก",
    loading: "กำลังโหลดข้อมูล...",
    nodata: "ไม่มีข้อมูล",
    confirm_delete_title: "ยืนยันการลบ",
    confirm_delete_msg: "คุณต้องการลบ",
    cancel: "ยกเลิก",
    popupform_title_addnew: "เพิ่มสินค้าใหม่",
    popupform_title_update: "แก้ไขสินค้า",
    signin_title: "Space Rantal",
    signin_subtitle: "ยินดีตอนรับเข้าสู่ระบบ",
    signin_username: "ชื่อผู้ใช้",
    signin_password: "รหัสผ่าน",
    signin_button_login: "เข้าสู่ระบบ",
    signin_remember: "จดจำรหัสผ่าน",
    signin_forgot_password: "ลืมระหัสผ่าน",
    language_text: "เปลี่ยนภาษา :",
  },
  en: {
    product_title: "Product and Service",
    product_mainpage: "Product",
    product_keyword: "Code/Product Name",
    product_button_create: "Add New",
    product_table_code: "Code",
    product_table_name1: "Name Thai",
    product_table_name2: "Name English",
    product_table_price: "Price/Unit",
    price: "Price",
    status: "Status",
    createdate: "Create Date",
    createby: "Create by",
    updatedate: "Update Date",
    updateby: "Update By",
    delete: "Delete",
    update: "Update",
    firstpage: "Home",
    prevpage: "Prevpage",
    lastpage: "LastPage",
    number: "Number",
    page: "Page",
    of: "Of",
    nextpage: "Next",
    record: "Records",
    reset: "Clear",
    back: "Back",
    loading: "Loading...",
    nodata: "Data not found.",
    confirm_delete_title: "Confirmation",
    confirm_delete_msg: "You want to delete ",
    cancel: "Cancel",
    popupform_title_addnew: "Add New",
    popupform_title_update: "Update",
    signin_title: "Space Rantal",
    signin_subtitle: "Sign in your account",
    signin_username: "Username",
    signin_password: "Password",
    signin_button_login: "Sign in",
    signin_remember: "Rememer me",
    signin_forgot_password: "Forgot password?",
    language_text: "Language :",
  },
};
export default translations;