const translations = {
    th: {
      dashboard: "แดชบอร์ด",
      booking: "จองพื้นที่",
      quotation: "ใบเสนอราคา",
      contract: "สัญญาเช่า",
      payment: "ชำระเงิน",
      expenses: "ค่าใช้จ่าย",
      invoice: "แจ้งหนี้",
      reports: "รายงาน",
      company: "บริษัท",
      customer: "ลูกค้า",
      products: "สินค้า",
      others: "อื่นๆ",
      database: "ฐานข้อมูล",
      language: "English",
      signout_button: "ออกจากระบบ",
      productgroup: "กลุ่มสินค้า",
      vattype:"ประเภทภาษี",
      paytype: "ประเภทชำระ",
      bank: "ธนาคาร",
    },
    en: {
      dashboard: "Dashboard",
      booking: "Booking",
      quotation: "Quotation",
      contract: "Contract",
      payment: "Payment",
      expenses: "Expenses",
      invoice: "Invoice",
      reports: "Reports",
      company: "Company",
      customer: "Customer",
      products: "Products & Service",
      others: "Others",
      database: "Database",
      language: "ไทย",
      signout_button: "Sign out",
      productgroup: "Product Group",
      vattype:"Vattype",
      paytype: "Paytype",
      bank: "Bank",
    },
  };
  
  export default translations;
  